video_editor/video_editor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [    path('admin/', admin.site.urls),   
path('', include('video_player.urls', namespace='video_player')),] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

video_editor/video_player/urls.py
from django.urls import path
from .views import *

app_name = 'video_player'

urlpatterns = [
    path('upload/', UploadVideoView.as_view(), name='video_upload'),
    path('<int:pk>/', VideoDetailView.as_view(), name='video_detail'),
    path('<int:pk>/edit/', EditVideoView.as_view(), name='video_edit'),
    path('<int:pk>/preview/', PreviewVideoView.as_view(), name='video_preview'),
    path('<int:pk>/download/', DownloadVideoView.as_view(), name='video_download'),
]

video_editor/video_player/models.py
from django.db import models

class Effect(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    effect = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Video(models.Model):
    title = models.CharField(max_length=255)
    video_file = models.FileField(upload_to='videos/')
    upload_date = models.DateTimeField(auto_now_add=True)
    description = models.TextField(default='') # add default value here
    image_file = models.ImageField(upload_to='images', null=True, blank=True)
    thumbnail = models.ImageField(upload_to='thumbnails', null=True, blank=True)

    def __str__(self):
        return self.title

video_editor/video_player/forms.py
from django import forms
from django.forms.widgets import ClearableFileInput
from .models import Video
from .models import Effect

# Define the choices for the effect field
EFFECT_CHOICES = (
    ('none', 'No effect'),
    ('grayscale', 'Grayscale'),
    ('sepia', 'Sepia'),
)

class VideoForm(forms.ModelForm):
    image = forms.ImageField()
    effect = forms.ChoiceField(choices=EFFECT_CHOICES)

    class Meta:
        model = Video
        fields = ['title', 'image', 'effect']

video_editor/video_player/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.http import HttpResponse, JsonResponse
from .forms import VideoForm
from .models import Video
import moviepy.editor as mp
from moviepy.editor import *
from django.contrib import messages
from tempfile import NamedTemporaryFile
import os
from django.conf import settings
from django.core.files import File


class UploadVideoView(View):
    template_name = 'upload_video.html'
    form_class = VideoForm
    success_url = reverse_lazy('video_player:video_detail')

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            video = form.save(commit=False)

            # Save the uploaded file to a temporary file
            with NamedTemporaryFile(delete=False) as f:
                f.write(video.video_file.read())
                video_filename = f.name
            with NamedTemporaryFile(delete=False) as f:
                f.write(video.thumbnail.read())
                thumbnail_filename = f.name

            # Process the video
            clip = mp.VideoFileClip(video_filename)
            clip = clip.resize(height=360)
            clip = clip.fx(mp.vfx.fadeout, duration=1)

            # Add text and image to the video
            txt_clip = (mp.TextClip("Hello World", fontsize=70, color='white')
                        .set_position('center')
                        .set_duration(clip.duration))
            img_clip = (mp.ImageClip(thumbnail_filename)
                        .set_duration(clip.duration)
                        .resize(height=50)
                        .set_position(('right','bottom')))
            final_clip = mp.CompositeVideoClip([clip, txt_clip, img_clip])

            # Save the processed video and thumbnail
            with open(video.video_file.path, 'wb+') as destination:
                for chunk in video.video_file.chunks():
                    destination.write(chunk)
            final_clip.write_videofile(video.video_file.path)
            
            with open(video.thumbnail.path, 'wb+') as destination:
                for chunk in video.thumbnail.chunks():
                    destination.write(chunk)
            final_clip.save_frame(video.thumbnail.path)
            
            # Save the video to the database
            video.save()

            messages.success(request, 'Video uploaded successfully.')
            return redirect(self.success_url, pk=video.pk)


class VideoDetailView(View):
    template_name = 'video_details.html'

    def get(self, request, pk):
        video = get_object_or_404(Video, pk=pk)
        return render(request, self.template_name, {'video': video})


class DownloadVideoView(View):
    def get(self, request, pk):
        video = Video.objects.get(pk=pk)
        file_path = video.video_file.path
        with open(file_path, 'rb') as f:
            response = HttpResponse(f.read(), content_type='video/mp4')
            response['Content-Disposition'] = 'attachment; filename=' + video.title + '.mp4'
            return response


class EditVideoView(View):
    model = Video
    form_class = VideoForm
    template_name = 'video_player/video_edit.html'

    def test_func(self):
        return self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('video_player:video_detail', kwargs={'pk': self.object.pk})

    def get(self, request, *args, **kwargs):
        # Implement GET method logic here
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        # Implement POST method logic here
        return super().post(request, *args, **kwargs)



    def get_preview_clip(self, file_path):
        video = mp.VideoFileClip(file_path)
        preview_clip = video.subclip(0, 5)  # preview only the first 5 seconds
        video.reader.close()
        video.audio.reader.close_proc()
        return preview_clip


class PreviewVideoView(View):
    def get(self, request, pk):
        video = get_object_or_404(Video, id=pk)
        video_path = video.video_file.path
        preview_clip = VideoFileClip(video_path).subclip(0, 5)
        preview_filename = f'{video.title}_preview.mp4'
        preview_dir = os.path.join(settings.MEDIA_ROOT, 'previews')
        preview_path = os.path.join(preview_dir, preview_filename)

        # Create previews directory if it doesn't exist
        if not os.path.exists(preview_dir):
            os.makedirs(preview_dir)

        preview_clip.write_videofile(preview_path, fps=24)
        return JsonResponse({'success': True})

video_editor/video_player/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

video_editor/video_player/templates/preview_video.html
{% extends 'base.html' %}

{% block content %}
  <h1>Preview Video - {{ video.title }}</h1>
  <video width="640" height="360" controls>
    <source src="{{ preview_clip }}" type="video/mp4">
    Your browser does not support the video tag.
  </video>
  <br>
  <a href="{% url 'video_player:video_edit' video.pk %}">Back to Editor</a>
{% endblock %}

video_editor/video_player/templates/upload_video.html
{% extends 'base.html' %}

{% block title %}Upload Video{% endblock %}

{% block content %}
    <h1>Upload Video</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
{% endblock %}

video_editor/video_player/templates/video_details.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ video.title }}</h1>
  <p>{{ video.description }}</p>
  <img src="{{ video.thumbnail.url }}" alt="{{ video.title }} thumbnail">
  <br>
  <a href="{% url 'video_player:video_edit' video.pk %}">Edit</a>
{% endblock %}

video_editor/video_player/templates/video_edit.html
{% extends 'video_player/base.html' %}

{% block content %}
  <h1>Edit Video</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Video</button>
  </form>
{% endblock %}

video_editor/video_player/templates/video_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Video List</h1>
  <ul>
    {% for video in videos %}
      <li>
        <a href="{% url 'video_detail' video.pk %}">{{ video.title }}</a>
        (<a href="{% url 'video_download' video.pk %}">Download</a>)
      </li>
    {% endfor %}
  </ul>
{% endblock %}